  
# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 03:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_details', '0005_auto_20180331_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            
        ),
        migrations.AddField(
            model_name='book',
            name='price_currency',
            
        ),
    ]